============================= test session starts ==============================
platform darwin -- Python 3.6.2, pytest-5.3.1, py-1.8.1, pluggy-0.13.1 -- /Library/Frameworks/Python.framework/Versions/3.6/bin/python3
cachedir: .pytest_cache
benchmark: 3.2.2 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: /Users/noah/Documents/UROP/lightning/tests/plugins
plugins: flaky-3.6.1, benchmark-3.2.2, forked-1.0.2, timeout-1.3.3, xdist-1.29.0
collecting ... collected 2 items

test_spider.py::test_regressive FAILED                                   [ 50%]
test_spider.py::test_regressive ERROR                                    [ 50%]
test_spider.py::test_payment_completion FAILED                           [100%]
test_spider.py::test_payment_completion ERROR                            [100%]

==================================== ERRORS ====================================
_____________________ ERROR at teardown of test_regressive _____________________

request = <SubRequest 'teardown_checks' for <Function test_regressive>>

    @pytest.fixture
    def teardown_checks(request):
        """A simple fixture to collect errors during teardown.
    
        We need to collect the errors and raise them as the very last step in the
        fixture tree, otherwise some fixtures may not be cleaned up
        correctly. Require this fixture in all other fixtures that need to either
        cleanup before reporting an error or want to add an error that is to be
        reported.
    
        """
        errors = TeardownErrors()
        yield errors
    
        if errors.has_errors():
            # Format a nice list of everything that went wrong and raise an exception
            request.node.has_errors = True
>           raise ValueError(str(errors))
E           ValueError: 
E           Node errors:
E            - lightningd-1: Node exited with return code 1
E            - lightningd-2: Node exited with return code 1
E            - lightningd-3: Node exited with return code 1
E           Global errors:

../../contrib/pyln-testing/pyln/testing/fixtures.py:150: ValueError
---------------------------- Captured stdout setup -----------------------------
Running tests in /tmp/ltests-i1vno1sz
DEBUG:root:Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_regressive_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG:root:Waiting for ['Done loading'] in the logs
DEBUG:root:Found 're.compile('Done loading')' in logs
INFO:root:BitcoinD started
------------------------------ Captured log setup ------------------------------
DEBUG    root:utils.py:154 Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_regressive_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG    root:utils.py:237 Waiting for ['Done loading'] in the logs
DEBUG    root:utils.py:259 Found 're.compile('Done loading')' in logs
INFO     root:utils.py:342 BitcoinD started
----------------------------- Captured stdout call -----------------------------
DEBUG:root:BitcoinRpcProxy proxying incoming port 50054 to 50042
DEBUG:root:BitcoinRpcProxy proxying incoming port 50055 to 50042
DEBUG:root:BitcoinRpcProxy proxying incoming port 50056 to 50042
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-1/ --addr=127.0.0.1:50048 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50054'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-2/ --addr=127.0.0.1:50050 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50056'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-3/ --addr=127.0.0.1:50052 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50055'
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:lightningd-2: 2020-03-26T19:48:53.330Z DEBUG plugin-manager: started(3147) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
----------------------------- Captured stderr call -----------------------------
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
------------------------------ Captured log call -------------------------------
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50054 to 50042
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50055 to 50042
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50056 to 50042
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-1/ --addr=127.0.0.1:50048 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50054'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-2/ --addr=127.0.0.1:50050 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50056'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-3/ --addr=127.0.0.1:50052 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50055'
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:206 lightningd-2: 2020-03-26T19:48:53.330Z DEBUG plugin-manager: started(3147) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
--------------------------- Captured stdout teardown ---------------------------
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:Test execution failed, leaving the test directory /tmp/ltests-i1vno1sz/test_regressive_1 intact.
---------------------------- Captured log teardown -----------------------------
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:fixtures.py:57 Test execution failed, leaving the test directory /tmp/ltests-i1vno1sz/test_regressive_1 intact.
_________________ ERROR at teardown of test_payment_completion _________________

request = <SubRequest 'teardown_checks' for <Function test_payment_completion>>

    @pytest.fixture
    def teardown_checks(request):
        """A simple fixture to collect errors during teardown.
    
        We need to collect the errors and raise them as the very last step in the
        fixture tree, otherwise some fixtures may not be cleaned up
        correctly. Require this fixture in all other fixtures that need to either
        cleanup before reporting an error or want to add an error that is to be
        reported.
    
        """
        errors = TeardownErrors()
        yield errors
    
        if errors.has_errors():
            # Format a nice list of everything that went wrong and raise an exception
            request.node.has_errors = True
>           raise ValueError(str(errors))
E           ValueError: 
E           Node errors:
E            - lightningd-1: Node exited with return code 1
E            - lightningd-2: Node exited with return code 1
E            - lightningd-3: Node exited with return code 1
E           Global errors:

../../contrib/pyln-testing/pyln/testing/fixtures.py:150: ValueError
---------------------------- Captured stdout setup -----------------------------
DEBUG:root:Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_payment_completion_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG:root:Waiting for ['Done loading'] in the logs
DEBUG:root:Found 're.compile('Done loading')' in logs
INFO:root:BitcoinD started
------------------------------ Captured log setup ------------------------------
DEBUG    root:utils.py:154 Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_payment_completion_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG    root:utils.py:237 Waiting for ['Done loading'] in the logs
DEBUG    root:utils.py:259 Found 're.compile('Done loading')' in logs
INFO     root:utils.py:342 BitcoinD started
----------------------------- Captured stdout call -----------------------------
DEBUG:root:BitcoinRpcProxy proxying incoming port 50075 to 50063
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-1/ --addr=127.0.0.1:50069 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50075'
DEBUG:root:BitcoinRpcProxy proxying incoming port 50076 to 50063
DEBUG:root:BitcoinRpcProxy proxying incoming port 50077 to 50063
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-2/ --addr=127.0.0.1:50071 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50076'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-3/ --addr=127.0.0.1:50073 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50077'
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:lightningd-2: 2020-03-26T19:48:57.264Z DEBUG plugin-manager: started(3164) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
Time-out: can't find [re.compile('Server started with public key')] in logs
DEBUG:root:Did not find 're.compile('Server started with public key')' in logs
----------------------------- Captured stderr call -----------------------------
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
------------------------------ Captured log call -------------------------------
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50075 to 50063
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-1/ --addr=127.0.0.1:50069 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50075'
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50076 to 50063
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50077 to 50063
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-2/ --addr=127.0.0.1:50071 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50076'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-3/ --addr=127.0.0.1:50073 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50077'
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:206 lightningd-2: 2020-03-26T19:48:57.264Z DEBUG plugin-manager: started(3164) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
DEBUG    root:utils.py:224 Did not find 're.compile('Server started with public key')' in logs
--------------------------- Captured stdout teardown ---------------------------
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Calling dev-memleak with payload None
DEBUG:root:Calling stop with payload None
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find '\*\*BROKEN\*\*' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Peer has reconnected' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad gossip order:' in logs
DEBUG:root:Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'Bad reestablish' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'bad hsm request' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'Accessing a null column' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:Did not find 'MEMLEAK:' in logs
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:BitcoinRpcProxy shut down after processing 0 requests
DEBUG:root:Test execution failed, leaving the test directory /tmp/ltests-i1vno1sz/test_payment_completion_1 intact.
---------------------------- Captured log teardown -----------------------------
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:lightning.py:277 Calling dev-memleak with payload None
DEBUG    root:lightning.py:277 Calling stop with payload None
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find '\*\*BROKEN\*\*' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Peer has reconnected' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad gossip order:' in logs
DEBUG    root:utils.py:224 Did not find 'gossipd.*Bad (?!gossip order from error)' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'Bad reestablish' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'bad hsm request' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'Accessing a null column' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:utils.py:224 Did not find 'MEMLEAK:' in logs
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:btcproxy.py:97 BitcoinRpcProxy shut down after processing 0 requests
DEBUG    root:fixtures.py:57 Test execution failed, leaving the test directory /tmp/ltests-i1vno1sz/test_payment_completion_1 intact.
=================================== FAILURES ===================================
_______________________________ test_regressive ________________________________

node_factory = <pyln.testing.utils.NodeFactory object at 0x106f37b00>
executor = <concurrent.futures.thread.ThreadPoolExecutor object at 0x106f37a58>

    def test_regressive(node_factory, executor):
        """Line graph with the middle node (l2) running the plugin.
        """
        l1, l2, l3 = node_factory.line_graph(
            3,  # We want 3 nodes
            opts=[{}, {'plugin': plugin_path}, {}],  # Start l2 with plugin
>           wait_for_announce=True  # Let nodes finish gossip before returning
        )

test_spider.py:16: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../contrib/pyln-testing/pyln/testing/utils.py:1018: in line_graph
    nodes = self.get_nodes(num_nodes, opts=opts)
../../contrib/pyln-testing/pyln/testing/utils.py:973: in get_nodes
    return [j.result() for j in jobs]
../../contrib/pyln-testing/pyln/testing/utils.py:973: in <listcomp>
    return [j.result() for j in jobs]
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py:405: in result
    return self.__get_result()
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py:357: in __get_result
    raise self._exception
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py:55: in run
    result = self.fn(*self.args, **self.kwargs)
../../contrib/pyln-testing/pyln/testing/utils.py:1008: in get_node
    node.start(wait_for_bitcoind_sync)
../../contrib/pyln-testing/pyln/testing/utils.py:652: in start
    self.daemon.start()
../../contrib/pyln-testing/pyln/testing/utils.py:529: in start
    self.wait_for_log("Server started with public key")
../../contrib/pyln-testing/pyln/testing/utils.py:271: in wait_for_log
    return self.wait_for_logs([regex], timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyln.testing.utils.LightningD object at 0x106fcc6d8>
regexs = ['Server started with public key'], timeout = 60

    def wait_for_logs(self, regexs, timeout=TIMEOUT):
        """Look for `regexs` in the logs.
    
        We tail the stdout of the process and look for each regex in `regexs`,
        starting from last of the previous waited-for log entries (if any).  We
        fail if the timeout is exceeded or if the underlying process
        exits before all the `regexs` were found.
    
        If timeout is None, no time-out is applied.
        """
        logging.debug("Waiting for {} in the logs".format(regexs))
        exs = [re.compile(r) for r in regexs]
        start_time = time.time()
        pos = self.logsearch_start
        while True:
            if timeout is not None and time.time() > start_time + timeout:
                print("Time-out: can't find {} in logs".format(exs))
                for r in exs:
                    if self.is_in_log(r):
                        print("({} was previously in logs!)".format(r))
                raise TimeoutError('Unable to find "{}" in logs.'.format(exs))
            elif not self.running:
>               raise ValueError('Process died while waiting for logs')
E               ValueError: Process died while waiting for logs

../../contrib/pyln-testing/pyln/testing/utils.py:249: ValueError
---------------------------- Captured stdout setup -----------------------------
Running tests in /tmp/ltests-i1vno1sz
DEBUG:root:Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_regressive_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG:root:Waiting for ['Done loading'] in the logs
DEBUG:root:Found 're.compile('Done loading')' in logs
INFO:root:BitcoinD started
------------------------------ Captured log setup ------------------------------
DEBUG    root:utils.py:154 Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_regressive_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG    root:utils.py:237 Waiting for ['Done loading'] in the logs
DEBUG    root:utils.py:259 Found 're.compile('Done loading')' in logs
INFO     root:utils.py:342 BitcoinD started
----------------------------- Captured stdout call -----------------------------
DEBUG:root:BitcoinRpcProxy proxying incoming port 50054 to 50042
DEBUG:root:BitcoinRpcProxy proxying incoming port 50055 to 50042
DEBUG:root:BitcoinRpcProxy proxying incoming port 50056 to 50042
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-1/ --addr=127.0.0.1:50048 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50054'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-2/ --addr=127.0.0.1:50050 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50056'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-3/ --addr=127.0.0.1:50052 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50055'
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:lightningd-2: 2020-03-26T19:48:53.330Z DEBUG plugin-manager: started(3147) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
----------------------------- Captured stderr call -----------------------------
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
------------------------------ Captured log call -------------------------------
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50054 to 50042
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50055 to 50042
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50056 to 50042
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-1/ --addr=127.0.0.1:50048 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50054'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-2/ --addr=127.0.0.1:50050 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50056'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_regressive_1/lightning-3/ --addr=127.0.0.1:50052 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50055'
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:206 lightningd-2: 2020-03-26T19:48:53.330Z DEBUG plugin-manager: started(3147) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
___________________________ test_payment_completion ____________________________

node_factory = <pyln.testing.utils.NodeFactory object at 0x107023dd8>
executor = <concurrent.futures.thread.ThreadPoolExecutor object at 0x107023e80>

    def test_payment_completion(node_factory, executor):
        l1, l2, l3 = node_factory.line_graph(
            3,  # We want 3 nodes
            opts=[{}, {'plugin': plugin_path}, {}],  # Start l2 with plugin
>           wait_for_announce=True  # Let nodes finish gossip before returning
        )

test_spider.py:40: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../../contrib/pyln-testing/pyln/testing/utils.py:1018: in line_graph
    nodes = self.get_nodes(num_nodes, opts=opts)
../../contrib/pyln-testing/pyln/testing/utils.py:973: in get_nodes
    return [j.result() for j in jobs]
../../contrib/pyln-testing/pyln/testing/utils.py:973: in <listcomp>
    return [j.result() for j in jobs]
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py:405: in result
    return self.__get_result()
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/_base.py:357: in __get_result
    raise self._exception
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/concurrent/futures/thread.py:55: in run
    result = self.fn(*self.args, **self.kwargs)
../../contrib/pyln-testing/pyln/testing/utils.py:1008: in get_node
    node.start(wait_for_bitcoind_sync)
../../contrib/pyln-testing/pyln/testing/utils.py:652: in start
    self.daemon.start()
../../contrib/pyln-testing/pyln/testing/utils.py:529: in start
    self.wait_for_log("Server started with public key")
../../contrib/pyln-testing/pyln/testing/utils.py:271: in wait_for_log
    return self.wait_for_logs([regex], timeout)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <pyln.testing.utils.LightningD object at 0x1070d5d30>
regexs = ['Server started with public key'], timeout = 60

    def wait_for_logs(self, regexs, timeout=TIMEOUT):
        """Look for `regexs` in the logs.
    
        We tail the stdout of the process and look for each regex in `regexs`,
        starting from last of the previous waited-for log entries (if any).  We
        fail if the timeout is exceeded or if the underlying process
        exits before all the `regexs` were found.
    
        If timeout is None, no time-out is applied.
        """
        logging.debug("Waiting for {} in the logs".format(regexs))
        exs = [re.compile(r) for r in regexs]
        start_time = time.time()
        pos = self.logsearch_start
        while True:
            if timeout is not None and time.time() > start_time + timeout:
                print("Time-out: can't find {} in logs".format(exs))
                for r in exs:
                    if self.is_in_log(r):
                        print("({} was previously in logs!)".format(r))
>               raise TimeoutError('Unable to find "{}" in logs.'.format(exs))
E               TimeoutError: Unable to find "[re.compile('Server started with public key')]" in logs.

../../contrib/pyln-testing/pyln/testing/utils.py:247: TimeoutError
---------------------------- Captured stdout setup -----------------------------
DEBUG:root:Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_payment_completion_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG:root:Waiting for ['Done loading'] in the logs
DEBUG:root:Found 're.compile('Done loading')' in logs
INFO:root:BitcoinD started
------------------------------ Captured log setup ------------------------------
DEBUG    root:utils.py:154 Starting 'bitcoind -datadir=/tmp/ltests-i1vno1sz/test_payment_completion_1 -printtoconsole -server -logtimestamps -nolisten -txindex -addresstype=bech32'
DEBUG    root:utils.py:237 Waiting for ['Done loading'] in the logs
DEBUG    root:utils.py:259 Found 're.compile('Done loading')' in logs
INFO     root:utils.py:342 BitcoinD started
----------------------------- Captured stdout call -----------------------------
DEBUG:root:BitcoinRpcProxy proxying incoming port 50075 to 50063
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-1/ --addr=127.0.0.1:50069 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50075'
DEBUG:root:BitcoinRpcProxy proxying incoming port 50076 to 50063
DEBUG:root:BitcoinRpcProxy proxying incoming port 50077 to 50063
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-2/ --addr=127.0.0.1:50071 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50076'
DEBUG:root:Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-3/ --addr=127.0.0.1:50073 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50077'
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:Waiting for ['Server started with public key'] in the logs
DEBUG:root:lightningd-2: 2020-03-26T19:48:57.264Z DEBUG plugin-manager: started(3164) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
Time-out: can't find [re.compile('Server started with public key')] in logs
DEBUG:root:Did not find 're.compile('Server started with public key')' in logs
----------------------------- Captured stderr call -----------------------------
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
lightningd: --dev-fast-gossip: unrecognized option
------------------------------ Captured log call -------------------------------
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50075 to 50063
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-1/ --addr=127.0.0.1:50069 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50075'
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50076 to 50063
DEBUG    root:btcproxy.py:92 BitcoinRpcProxy proxying incoming port 50077 to 50063
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-2/ --addr=127.0.0.1:50071 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --plugin=/Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py --bitcoin-rpcport=50076'
DEBUG    root:utils.py:154 Starting 'lightningd --log-level=debug --cltv-delta=6 --cltv-final=5 --watchtime-blocks=5 --rescan=1 --disable-dns --lightning-dir=/tmp/ltests-i1vno1sz/test_payment_completion_1/lightning-3/ --addr=127.0.0.1:50073 --allow-deprecated-apis=false --network=regtest --ignore-fee-limits=false --bitcoin-rpcuser=rpcuser --bitcoin-rpcpassword=rpcpass --dev-fast-gossip --dev-bitcoind-poll=1 --dev-fail-on-subdaemon-fail --dev-no-reconnect --bitcoin-rpcport=50077'
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:237 Waiting for ['Server started with public key'] in the logs
DEBUG    root:utils.py:206 lightningd-2: 2020-03-26T19:48:57.264Z DEBUG plugin-manager: started(3164) /Users/noah/Documents/UROP/lightning/tests/plugins/spider_routing.py
DEBUG    root:utils.py:224 Did not find 're.compile('Server started with public key')' in logs
==================== 2 failed, 2 errors in 67.50s (0:01:07) ====================
